### PR TITLE
Fix PEP8 errors and warnings

### PR DESCRIPTION
**Pull request by neteler**
Prior to adding some "flake8" tests into GitHub Actions, we need to minimize the PEP8 errors and warnings.

This PR adresses:
- PEP8: fix `E228 missing whitespace around modulo operator`
- PEP8: fix `E201 whitespace after '('`
- PEP8: fix `E203 whitespace before ':'`
- PEP8: fix `E241 multiple spaces after ','`
- PEP8: fix `W391 blank line at end of file`
- PEP8: fix `E401 multiple imports on one line`
- PEP8: fix `E222 multiple spaces after operator`

by having run:
```
# XXX being the respective error/warning code
ag --python -l | xargs autopep8 --select XXX --in-place
```

See individual commits for details.

### CODE REVIEW

**Review by griembauer — COMMENTED** [review]
Shouldn't there be a whitespace after the modulo operator too? i.e. `URL_PREFIX="/api/%s" % API_VERSION`?

**Review by mmacata — APPROVED** [review]
Thanks for that! Please merge.

**Comment by neteler** [comment]
> Shouldn't there be a whitespace after the modulo operator too? i.e. `URL_PREFIX="/api/%s" % API_VERSION`?

I thought the same. But 
- autopep8 didn't add that
- flake8 no longer complains about E228 (while I see https://www.flake8rules.com/rules/E228.html)

No idea...

**Review by AnikaBettge — APPROVED** [review]

**Review by griembauer — APPROVED** [review]

**Comment by neteler** [comment]
> Shouldn't there be a whitespace after the modulo operator too? i.e. `URL_PREFIX="/api/%s" % API_VERSION`?

(found it, it is E225: addressed in #110)

**Pull request merged**
