### PR TITLE
Update docker alpine to 3.15

### PR DESCRIPTION
**Pull request by mmacata**
- update requirements.txt

### CODE REVIEW

**Comment by metzm** [comment]
The error when installing pyproj is `ERROR: Minimum supported PROJ version is 8.0.0, installed version is 7.0.1. `

Should be easy to solve by enforcing pyproj 2.6, see pyproj [version compatibility matrix](https://pyproj4.github.io/pyproj/stable/installation.html#installing-from-source).

**Comment by mmacata** [comment]
Where do you see this error? This exact requirements was changed for alpine as with alpine 3.15, proj 8.2.0 is contained. The error in the pipeline seems a bit odd:
```
#18 7.993 ERROR: Could not find a version that satisfies the requirement pyproj>=3.3.0 (from versions: 1.8.0, 1.8.1a0, 1.8.1, 1.9.3, 1.9.4, 1.9.5, 1.9.5.1, 1.9.6, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.2.post1, 2.5.0, 2.6.0, 2.6.1, 2.6.1.post1, 3.0rc2, 3.0.0, 3.0.0.post1, 3.0.1, 3.1.0, 3.2.0, 3.2.1, 3.3.0)
920
#18 7.993 ERROR: No matching distribution found for pyproj>=3.3.0
```

**Comment by metzm** [comment]
Here https://github.com/mundialis/actinia_core/runs/5322144790?check_suite_focus=true#step:5:916

```
#18 7.990   ERROR: Minimum supported PROJ version is 8.0.0, installed version is 7.0.1. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
```

**Comment by mmacata** [comment]
Ah ok - locally I already tested with alpine 3.15, so this should be fine. I thought you saw it somewhere else.

**Comment by mmacata** [comment]
Duplicate of newer version https://github.com/mundialis/actinia_core/pull/343, closing this.

**Pull request closed without merging**
