### PR TITLE
cleaning documentation in actinia_core/docs/docs

### PR DESCRIPTION
**Pull request by juleshaas**
This MR updates various proofread docs.md in actinia_core/docs/docs.

### CODE REVIEW

**Comment by mmacata** [comment]
Hi @juleshaas - is this still work in progress or can it be moved out of draft status and is ready to be merged?

**Comment by juleshaas** [comment]
The overview table in actinia_concepts.md still does not render nicely. I'll try to see to it soon.

**Comment by mmacata** [comment]
Ah ok - but you didn't break anything, it is already broken: https://github.com/mundialis/actinia_core/blob/main/docs/docs/actinia_concepts.md#user-user-roles-and-user-groups
so no need. (But if you like to fix it, I won't hinder you of cource ;) )

**Review by mmacata — APPROVED** [review]

**Comment by mmacata** [comment]
Thanks! Please merge!

**Comment by juleshaas** [comment]
Ok, I'll merge now.

**Pull request merged**
