### PR TITLE
raise AsyncProcessError if mapset-lock to be checked does not exist

### PR DESCRIPTION
**Pull request by griembauer**
When the `api/v1/locations/<location>/mapsets/<mapsets>/lock` endpoint is used to check whether a mapset is locked, the process is successful and the actinia response contains
```
[...]  
"message": "Mapset lock state: False",
"process_chain_list": [],
"process_log": [],
"process_results": false,
[...]
```
even if the mapset does not exist. With this PR, an `AsyncProcessError` is raised if the combination of location and mapset to be checked for a lock does not exist. In case *not* raising an error is a desired behaviour, there might be another option to let the user know the mapset does not exist, e.g. by providing a different `self.finish_message`.

### CODE REVIEW

**Review by anikaweinmann — APPROVED** [review]

**Comment by anikaweinmann** [comment]
@griembauer can you please still look at the error in the test? ERROR in: tests/test_mapset_management.py::MapsetTestCase::test_mapset_creation_and_locking
--> /src/actinia_core/tests/test_mapset_management.py:197: AssertionError: 400 != 200 : HTML status code is wrong 400

**Comment by griembauer** [comment]
> @griembauer can you please still look at the error in the test? ERROR in: tests/test_mapset_management.py::MapsetTestCase::test_mapset_creation_and_locking
> --> /src/actinia_core/tests/test_mapset_management.py:197: AssertionError: 400 != 200 : HTML status code is wrong 400

Thanks for pointing this out, the status code changed to 400 so this is now also adapted in the test. However, there is one open question: The last test of `/src/actinia_core/tests/test_mapset_management.py` is a deletion of a lock of a non-existing mapset, which expects a status code 200. Following the logic of this PR, there should also be a status code 400 and an exception raised that this mapset does not exist. Unless of course, it is desired to **not** throw an Exception.

**Comment by mmacata** [comment]
I like the idea that a user will be informed that the mapset does not exist instead of assuming it is not locked.
How does the response look like? I would't mind the `AsyncProcessError` if the user is informed accordingly - and maybe HTTP status code `404` - Not Found might fit a bit better.
I also agree on the changes to `/src/actinia_core/tests/test_mapset_management.py` - the DELETE method should return a similar response to the HTTP GET method with code 400 / 404 as well.

**Comment by griembauer** [comment]
The methods are now adapted to match existing methods in `mapset_management.py` and `persistent_processing.py`. Now an error is also raised if a non-existing mapset is unlocked. The error messages are:

- trying to get the lock status of a non-existing mapset: `"AsyncProcessError:  Unable to get lock status of mapset <mapset> in location <location>: Mapset does not exist"`
- trying to unlock a non-existing mapset: `AsyncProcessError:  Unable to unlock mapset <mapset> in location <location>: Mapset does not exist`

Trying to lock a non-existing mapset already fais with a similar error message before this PR.
However I am unsure how to manipulate the http code, @mmacata can you point me to where this could be implemented?

**Comment by mmacata** [comment]
Great!
For the status code - I didn't know this endpoint enqueues the job as well. Then it is much harder and 400 is fine for me. It most likely comes from [here](https://github.com/mundialis/actinia_core/blob/master/src/actinia_core/resources/ephemeral_processing.py#L502) and is - without custom code - not easy to change. It could be overwritten [here](https://github.com/mundialis/actinia_core/blob/83db2e48e1708a3137060f8e138ecf694fb0fa88/src/actinia_core/resources/mapset_management.py#L541), but as an exception is raised, the code might propably not execute up to this point.

So all fine from my point of view!

**Review by mmacata — APPROVED** [review]

**Comment by griembauer** [comment]
Thanks for the additional info and the review! I will merge now

**Pull request merged**
